spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mmall_learning
    username: root
    password: 1234


ftp:
  server:
    ip: 192.168.58.23
    port: 21
    username: mercurybpm
    password: mercury_sx123
